from bot import CMD_INDEX


class _BotCommands:
    def __init__(self):
       self.StartCommand = f'pmstart{CMD_INDEX}'
        self.MirrorCommand = f'pm{CMD_INDEX}'
        self.UnzipMirrorCommand = f'pmunzipmirror{CMD_INDEX}'
        self.ZipMirrorCommand = f'pmzipmirror{CMD_INDEX}'
        self.CancelMirror = f'pmcancel{CMD_INDEX}'
        self.CancelAllCommand = f'pmcancelall{CMD_INDEX}'
        self.ListCommand = f'pmlist{CMD_INDEX}'
        self.SearchCommand = f'pmsearch{CMD_INDEX}'
        self.StatusCommand = f'pmstatus{CMD_INDEX}'
        self.AuthorizedUsersCommand = f'pmusers{CMD_INDEX}'
        self.AuthorizeCommand = f'pmauthorize{CMD_INDEX}'
        self.UnAuthorizeCommand = f'pmunauthorize{CMD_INDEX}'
        self.AddSudoCommand = f'pmaddsudo{CMD_INDEX}'
        self.RmSudoCommand = f'pmrmsudo{CMD_INDEX}'
        self.PingCommand = f'pmping{CMD_INDEX}'
        self.RestartCommand = f'pmrestart{CMD_INDEX}'
        self.StatsCommand = f'pmstats{CMD_INDEX}'
        self.HelpCommand = f'pmhelp{CMD_INDEX}'
        self.LogCommand = f'pmlog{CMD_INDEX}'
        self.SpeedCommand = f'pmspeedtest{CMD_INDEX}'
        self.CloneCommand = f'pmclone{CMD_INDEX}'
        self.CountCommand = f'pmcount{CMD_INDEX}'
        self.WatchCommand = f'pmwatch{CMD_INDEX}'
        self.ZipWatchCommand = f'pmzipwatch{CMD_INDEX}'
        self.QbMirrorCommand = f'pmqbmirror{CMD_INDEX}'
        self.QbUnzipMirrorCommand = f'pmqbunzipmirror{CMD_INDEX}'
        self.QbZipMirrorCommand = f'pmqbzipmirror{CMD_INDEX}'
        self.DeleteCommand = f'pmdel{CMD_INDEX}'
        self.ShellCommand = f'pmshell{CMD_INDEX}'
        self.ExecHelpCommand = f'pmexechelp{CMD_INDEX}'
        self.LeechSetCommand = f'pmleechset{CMD_INDEX}'
        self.SetThumbCommand = f'pmsetthumb{CMD_INDEX}'
        self.LeechCommand = f'pmleech{CMD_INDEX}'
        self.UnzipLeechCommand = f'pmunzipleech{CMD_INDEX}'
        self.ZipLeechCommand = f'pmzipleech{CMD_INDEX}'
        self.QbLeechCommand = f'pmqbleech{CMD_INDEX}'
        self.QbUnzipLeechCommand = f'pmqbunzipleech{CMD_INDEX}'
        self.QbZipLeechCommand = f'pmqbzipleech{CMD_INDEX}'
        self.LeechWatchCommand = f'pmleechwatch{CMD_INDEX}'
        self.LeechZipWatchCommand = f'pmleechzipwatch{CMD_INDEX}'
        self.RssListCommand = f'pmrsslist{CMD_INDEX}'
        self.RssGetCommand = f'pmrssget{CMD_INDEX}'
        self.RssSubCommand = f'pmrsssub{CMD_INDEX}'
        self.RssUnSubCommand = f'pmrssunsub{CMD_INDEX}'
        self.RssUnSubAllCommand = f'pmrssunsuball{CMD_INDEX}'
BotCommands = _BotCommands()
